#!/bin/sh
workspace_dir="$( cd "$( dirname "$0" )" && pwd )"
cd $workspace_dir
export GIT_DIR=./.apocalypse

if test -e .apocalypse/
then
  git checkout -q -f default
else
  git init -q
fi

echo "$(date +%s)" > .beginning

git config user.name "dojo"
git config user.email "email@example.com"
git add -f -A .
git commit -q -m "beginning"

git checkout -q -f -b "$(date +%s)" HEAD
# ./metronome &

echo "# \n# Beginning the apocalypse workspace at $workspace_dir \n# "
