#!/bin/sh
workspace_dir="$( cd "$( dirname "$0" )" && pwd )"
cd $workspace_dir

exec_time="$(date --rfc-3339=seconds)"

if test -e .git/
then
  git checkout -q -f default
else
  git init -q
fi

echo "$(date +%s)" >> .beginning

git config user.name "dojo"
git config user.email "email@example.com"
git add .
git commit -q -m "beginning at $exec_time"

git checkout -q -f -b "$(date +%s)" HEAD

echo "# \n# Beginning the apocalyse workspace at $workspace_dir \n# "
