#!/bin/sh
workspace_dir="$( cd "$( dirname "$0" )" && pwd )"
cd $workspace_dir

if test -e .git/
then
  git checkout -f default
else
  git init -q
fi

echo "$(date +%s)" >> .beggining

git config user.name "dojo"
git config user.email "email@example.com"
git add .
git commit -q -m "beginning at $exec_time"

git checkout -f -b "$(date +%s)" HEAD

echo "# \n# Beginning the apocalyse workspace at $workspace_dir \n# "
