#!/bin/sh
workspace_dir="$( cd "$( dirname "$0" )" && pwd )"
cd $workspace_dir
export GIT_DIR=./.apocalypse

./runtests
if test $? -eq 0
then
  echo "$(date +%s)" > .beginning
  git add -f -A .
  git commit -q -m "commit"
else
  echo "Tests Failed, so no check-in for you!"
fi
