#!/bin/sh
workspace_dir="$( cd "$( dirname "$0" )" && pwd )"
cd $workspace_dir

exec_time="$(date --rfc-3339=seconds)"

git init -q
git add .
git commit -q -m "auto at $exec_time" --author="dojo <email@example.com>"

