#!/bin/sh
workspace_dir="$( cd "$( dirname "$0" )" && pwd )"
cd $workspace_dir

exec_time="$(date --rfc-3339=seconds)"

git add .
status="$(git status --porcelain)"

if test -n $status
then
  git commit -q -m "revert at $exec_time"
  git checkout -f -b "$(date +%s)" HEAD^
fi

git checkout -f HEAD
