#!/bin/sh
workspace_dir="$( cd "$( dirname "$0" )" && pwd )"
cd $workspace_dir
export GIT_DIR=./.apocalypse

git add -f -A .

if test -n "$(git status --porcelain)"
then
  git commit -q -m "revert"
  git checkout -q -f -b "$(date +%s)" HEAD^
fi

git checkout -q -f HEAD
